name = "replate-static-website"
compatibility_date = "2025-09-04"
preview_urls = false

routes = [
    { pattern = "www.replate.dev", custom_domain = true },
]

[assets]
directory = "./static"
not_found_handling = "single-page-application"