name = "replate-business-spa"
compatibility_date = "2025-09-03"
preview_urls = false
workers_dev = false

routes = [
    { pattern = "business.replate.dev/*", zone_name = "replate.dev" }
]

[build]
command = "npm run build"

[assets]
directory = "./public"
not_found_handling = "single-page-application"

