# Creates a Cloudflare D1 database for CRM data. A future worker/API will connect to this DB.
resource "cloudflare_d1_database" "crm" {
  account_id = var.cloudflare_account_id
  name       = var.cloudflare_d1_db_name
  primary_location_hint = "apac"
  read_replication = {
    mode = "disabled"
  }
}

output "cloudflare_d1_crm_id" {
  description = "ID of the Cloudflare D1 CRM database"
  value       = cloudflare_d1_database.crm.id
}

output "cloudflare_d1_crm_name" {
  description = "Name of the Cloudflare D1 CRM database"
  value       = cloudflare_d1_database.crm.name
}

# Generate wrangler.toml file for the CRM directory
resource "local_file" "crm_wrangler_toml" {
  filename = "${path.module}/../crm/wrangler.toml"
  content  = <<-EOT
# Autogenerated by Terraform
[[d1_databases]]
binding = "DB"
database_name = "${cloudflare_d1_database.crm.name}"
database_id = "${cloudflare_d1_database.crm.id}"
EOT
}
