all: deploy

deploy:
	wrangler deploy

.PHONY: deploy

help:
	@echo "Available targets:"
	@echo "  all (default) - Build the project"
	@echo "  build         - Build the project"
	@echo "  dev           - start local dev"
	@echo "  help          - Show this help message"