name = "replate-admin-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
preview_urls = false

routes = [
    { pattern = "admin.replate.dev/api/*", zone_name = "replate.dev" }
]

[build]
command = "npm run build"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
# Set these via Terraform or wrangler secrets in real envs
AUTH0_JWKS_URL = "https://id.replate.dev/.well-known/jwks.json"
AUTH0_AUDIENCE_ADMIN = "admin.api"
AUTH0_ISSUER = "https://id.replate.dev/"

[[d1_databases]]
binding = "DB"
database_name = "replate-admin"
database_id = "2e03b343-2b17-4adc-850f-82f6c1b58dea"